stages:
  - prepare
  - test
  - release

image: cookielab/nodejs:8

yarn:
  stage: prepare
  tags:
    - docker
  script:
    - yarn
  cache:
    paths:
      - node_modules
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

lint:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  script:
    - bin/lint

publish:
  stage: release
  tags:
    - docker
  dependencies: []
  before_script:
    - echo "$NPMRC" > ~/.npmrc
  script:
    - npm version "$CI_COMMIT_TAG" --no-git-tag-version --allow-same-version
    - npm publish --verbose
  only:
    - tags

github:
  stage: release
  tags:
    - docker
  dependencies: []
  image: cookielab/git-mirror:2.15
  before_script:
    - eval $(ssh-agent -s)
    - import-ssh-key
    - git config --global user.email "robot@cookielab.io"
    - git config --global user.name "Cookie Monster"
  script:
    - git remote rm mirror || true
    - git remote add mirror git@github.com:cookielab/eslint-config-server.git
    - git checkout -B master origin/master
    - git push mirror master
    - git push mirror master --tags
  only:
    - tags
