module.exports = {
	plugins: [
		'import',
	],
	rules: {
		'import/default': 'error',
		'import/dynamic-import-chunkname': 'off',
		'import/export': 'error',
		'import/exports-last': 'off',
		'import/extensions': ['error', 'never', {json: 'ignorePackages'}],
		'import/first': 'off',
		'import/group-exports': 'off',
		'import/max-dependencies': 'off',
		'import/named': 'error',
		'import/namespace': 'error',
		'import/newline-after-import': 'error',
		'import/no-absolute-path': 'error',
		'import/no-amd': 'error',
		'import/no-anonymous-default-export': ['error', {
			allowArray: true,
			allowArrowFunction: false,
			allowAnonymousClass: false,
			allowAnonymousFunction: false,
			allowCallExpression: false,
			allowLiteral: false,
			allowObject: true,
		}],
		'import/no-commonjs': 'error',
		'import/no-cycle': 'off',
		'import/no-default-export': 'off',
		'import/no-deprecated': 'off',
		'import/no-duplicates': 'error',
		'import/no-dynamic-require': 'off',
		'import/no-extraneous-dependencies': 'off',
		'import/no-internal-modules': 'off',
		'import/no-mutable-exports': 'off',
		'import/no-named-as-default': 'warn',
		'import/no-named-as-default-member': 'warn',
		'import/no-named-default': 'off',
		'import/no-named-export': 'off',
		'import/no-namespace': 'off',
		'import/no-nodejs-modules': 'off',
		'import/no-relative-parent-imports': 'off',
		'import/no-restricted-paths': 'off',
		'import/no-self-import': 'off',
		'import/no-unassigned-import': 'off',
		'import/no-unresolved': 'error',
		'import/no-useless-path-segments': 'off',
		'import/no-webpack-loader-syntax': 'off',
		'import/order': 'off',
		'import/prefer-default-export': 'off',
		'import/unambiguous': 'off',
	},
};
